apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp3-deploy
spec:
  selector:
    matchLabels:
      app: myapp3
  replicas: 3
  template:
    metadata:
      name: myapp3-pod
      labels:
        app: myapp3
    spec:
      containers:
        - name: myapp3
          image: stacksimplify/kubenginx:3.0.0
          ports:
            - containerPort: 80