apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp2-rs
spec:
  selector:
    matchLabels:
      app: myapp2
  replicas: 3
  template:
    metadata:
      name: myapp2-pod
      labels:
        app: myapp2
    spec:
      containers:
        - name: myapp2
          image: stacksimplify/kubenginx:2.0.0
          ports:
            - containerPort: 80
               
